### ISSUE TITLE
Problem using SegmentedBar

### ISSUE THREAD

**Issue by Lelelo1** [shirakaba/react-nativescript#35]
I get the following error using `$SegmentedBar` in my tsx:

![UsingSegmentedBar](https://user-images.githubusercontent.com/42244983/62872862-9f40bf80-bd1e-11e9-848e-8765684e2b3c.png)

> file:///node_modules/tslib/tslib.es6.js:121:0 JS ERROR TypeError: undefined is not an object (evaluating 'o[Symbol.iterator]')

**Comment by shirakaba** [comment]
Not a known error... I'll need more information here.

## Check that you're navigating to the page correctly

How are you navigating to this page? I'd usually expect `this.pageRef` to be passed in as a prop (e.g. `this.props.forwardedRef`), unless you've got a $Frame wrapping that $Page.

## Check your Page's children

I don't know what AppBar and MainScreen correspond to, but I should clarify that a $Page can only take one content child (it's a single-view component).

There are certain technicalities to this:

You can nest extra $Pages inside any $Page (I make a [special exception](https://github.com/shirakaba/react-nativescript/blob/master/react-nativescript/src/client/HostConfig.ts#L420) to allow this pattern, as it makes navigation much easier to set up; $Pages always establish a new, detached, component tree). In other words, $Page does not act as a content child.

ActionBar also does not act as a content child ([it updates the `actionBar` property](https://github.com/shirakaba/react-nativescript/blob/master/react-nativescript/src/client/HostConfig.ts#L423) rather than [the `content` property](https://github.com/shirakaba/react-nativescript/blob/master/react-nativescript/src/client/HostConfig.ts#L430)).

## I may have implemented $SegmentedBar incorrectly

I'm not totally sure what a SegmentedBar is. I made a brief test with it, then moved on. I may need to revisit it.

* https://docs.nativescript.org/ui/ns-ui-widgets/segmented-bar
* https://github.com/NativeScript/nativescript-sdk-examples-js/tree/master/app/ns-ui-widgets-category/segmented-bar

## Minimal reproduction

Could you reproduce this as a minimum working example (something that I can run)? Without knowing the code around that code snippet, it's a bit hard for me to reproduce.

**Comment by Lelelo1** [comment]
I created a [repro sample](https://github.com/Lelelo1/ReproSegmentedBar.git) following the steps to create a new project.

The image does not correspond to how I initially used it (wrapped in layout indeed). I was in a hurry so I copied it into the project of the image - but it does produce the same error.

I also checked in vanilla ts Nativescript project. There is no error from simply adding the component (into a layout).

**Comment by shirakaba** [comment]
Perfect, that helps a lot!

I can see a problem here. $Page is a single-view component. I believe the React HostConfig will first encounter the $Label child and add that as the content view, then it will find the next component ($SegmentedBar) and will use that at the $Page's content view instead.

For both to be visible at the same time, They'd need to be nested together in a $StackLayout.

Does the error stop if you:

1. Comment-out the $Label component?
2. And otherwise, if you nest the $Label and $SegmentedBar together in a $StackLayout?

I'll be able to play with the code in a few hours, but for now, if you could answer both of those questions, we'd be able to determine whether it's a library bug or simply incorrect usage of $SegmentedBar.

**Comment by shirakaba** [comment]
A quick thought: ```TypeError: undefined is not an object (evaluating 'o[Symbol.iterator]')``` makes me think that the React Host Config may be trying to iterate over an array of children or some other array-like property on the `Page`, but that array is found to be undefined. But maybe it's something else entirely.

**Comment by Lelelo1** [comment]
There is no problem when adding the `SegmentedControl` manually in `componentDidMount` to the layout.

There is an `items` array property on the component - so it is not intended to take children I believe. Also there is no `$SegmentedBarItem` to declare in the tsx.

**Comment by shirakaba** [comment]
> There is an `items` array property on the component - so it is not intended to take children I believe.

It supports the [addition of SegmentedBarItem children](https://github.com/shirakaba/react-nativescript/blob/master/react-nativescript/src/client/HostConfig.ts#L453), but as you say, it seems I haven't implemented a `$SegmentedBarItem` component. Sorry about that, I'll add one.

Sounds like I'd better run the repro and see what needs implementing in the library. Hopefully I'll have some time to do that this evening.

**Comment by Lelelo1** [comment]
Again, the error is thrown from simply declaring `$SegmentedBar` anywhere.

So if page and frame is removed in `AppContainer` and replaced with `$SegmentedBar` (only) - the error is thrown:

```
render() {
    return(
        <$SegmentedBar />
    );
}
```
There is no error about failed to create page etc - or crash beacuse there is no frame.

**Comment by shirakaba** [comment]
I've identified a fix for the issue; will create a $SegmentedBarItem component as well before pushing the patch.

**Comment by shirakaba** [comment]
Issue closed in version 0.11.0 – see my example SegmentedBar [code snippet](https://github.com/shirakaba/react-nativescript/blob/22cffe7b5439c7ab4e7ce6b495bba31ce38a6c1e/sample/app/testComponents/testComponents.tsx#L209). Thanks for the report!

<img width="447" alt="SegmentedBar fixed" src="https://user-images.githubusercontent.com/14055146/62983070-09905780-be26-11e9-9863-9c2f0e19f0e2.png">
