### ISSUE TITLE
Unable to use $GridLayout in jsx/tsx

### ISSUE THREAD

**Issue by Lelelo1** [shirakaba/react-nativescript#38]
![$GridLayout](https://user-images.githubusercontent.com/42244983/64418025-7f40b980-d09a-11e9-9af6-441147aa0278.png)

Using `"react-nativescript": "^0.11.0",`. And there appears to be no problem creating GridLayouts in componentDidMount and adding them.

**Comment by shirakaba** [comment]
I may have made `children` mandatory for that component (evidently a bad idea); does the error resolve upon adding a child component?

**Comment by shirakaba** [comment]
Wait, forget that, I misread it.

See at the end of the message that the `rows` and `columns` properties are missing.

In NativeScript Core, those are optional, but in React NativeScript, I set them up as mandatory. I'll have to amend that. In the meantime, you should write:

```js
<$GridLayout rows={[]} columns={[]}>
</$GridLayout>
```

See my sample app for examples of how to fill in the `rows` and `columns` properties on GridLayout in React NativeScript v0.11.0:

https://github.com/shirakaba/rpstrackerrns/blob/master/app/views/pages/detail/DetailPage.tsx#L604

In a future version of RNS, I'd like to accept strings instead of the strongly-typed ItemSpecs here, as they're very annoying to write out.

**Comment by Lelelo1** [comment]
```
<$GridLayout rows={[]} columns={[]}>
    <$Button />
</$GridLayout>
```
-->

![Screenshot 2019-09-06 at 12 57 32](https://user-images.githubusercontent.com/42244983/64423065-e6b03680-d0a5-11e9-8b22-a4b46d54103a.png)

```
<$GridLayout rows={[{}]} columns={[{}]}>
    <$Button />
</$GridLayout>
```

-->
![Screenshot 2019-09-06 at 12 58 52](https://user-images.githubusercontent.com/42244983/64423155-17906b80-d0a6-11e9-8612-cc71055dd85b.png)

**Comment by Lelelo1** [comment]
This worked actually:

```
<$GridLayout rows={[]} columns={[]}>

</$GridLayout>
```

I copied over the code rpstrackerrns and removed bit after bit.
