### ISSUE TITLE
Idea: use with another VDOM library

### ISSUE THREAD

**Issue by brodybits** [shirakaba/react-nativescript#40]
such as Preact (preact-nativescript?), Inferno, or even the [rawact Babel plugin](https://github.com/ankeetmaini/rawact)?

**Comment by shirakaba** [comment]
React NativeScript is coupled to React. I can't just pick up this implementation and migrate it to another renderer. It would be a full library rewrite.

Vue implemented a [DOM for NativeScript](https://github.com/nativescript-vue/nativescript-vue/tree/master/platform/nativescript/renderer), and Svelte Native [built upon it](https://github.com/halfnelson/svelte-native/tree/master/src/dom). Those two implementations are far more suitable for migrating to another renderer.

[NativeScript Preact](https://github.com/staydecent/nativescript-preact) and [Preact to NativeScript](https://github.com/hizoul/preact-to-nativescript) both exist, and died out either due to difficulty in implementation or due to lack of interest/contribution.

rawact is still in proof-of-concept stage and is incomplete.

If Inferno is *completely* API-compatible with React, right down to the TypeScript typings, then there might be a chance of porting it. However, I have no experience with it, and am still trying to get this project off the ground, so I have no interest in abandoning this project to start afresh with an even more niche one.
