### ISSUE TITLE
Template not creating .gitignore and has an .awcache folder.

### ISSUE THREAD

**Issue by spacesuitdiver** [shirakaba/react-nativescript#52]
Sorry if this is another repo or in this repo and I could have linked to the code or even PR'd, I have no idea how nativescript templates work 😬 

Anyway, the template has a couple of things missing/included that I wouldn't expect in a more general template or compared to nativescript core's template.

There's a `tools/dot.gitignore` instead of a typical `.gitignore` and there's a `.awcache` folder.

**Comment by shirakaba** [comment]
Thanks! By chance I noticed this issue last night when initialising a project from the template, and so have fixed it in the latest template, `v6.5.1`, which is implicitly used by NativeScript CLI version `6.5.x`.

The template repo is here. I’ll link to it from more places later because I keep having to search my own repos to find it again each time: https://github.com/shirakaba/tns-template-blank-react
